const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
let currentRunId=null,currentJobId=null,currentCompany=null,pollTimer=null;
const titles={dashboard:'Visão geral',prospecting:'Prospecção',crm:'CRM',ai:'IA Hub',whatsapp:'WhatsApp',diagnostics:'Diagnóstico'};
function toast(msg,type=''){const el=$('#toast');el.textContent=msg;el.className='toast show '+type;setTimeout(()=>el.className='toast',2800)}
async function api(url,options={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});let d;try{d=await r.json()}catch{d={error:`HTTP ${r.status}`}}if(r.status===401){location.href='/login';throw new Error('Sessão expirada')}if(!r.ok)throw new Error(d.error||d.erro||`HTTP ${r.status}`);return d}
function tab(name){$$('.tab').forEach(x=>x.classList.toggle('active',x.id===`tab-${name}`));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));$('#pageTitle').textContent=titles[name]||name;if(name==='dashboard')loadDashboard();if(name==='crm')loadCRM();if(name==='ai')loadAI();if(name==='whatsapp')loadWhatsApp();if(name==='diagnostics')diagnostics(false)}
$$('.nav').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$$('[data-go]').forEach(b=>b.onclick=()=>tab(b.dataset.go));
$('#logoutBtn').onclick=async()=>{await api('/api/logout',{method:'POST',body:'{}'});location.href='/login'};
async function loadDashboard(){try{const d=await api('/api/dashboard');const metrics=[['total','Empresas'],['novos_hoje','Novos hoje'],['sem_site','Sem site'],['wa_elegiveis','WA elegíveis'],['interessados','Interessados'],['fechados','Fechados']];$('#metrics').innerHTML=metrics.map(([k,l])=>`<div class="metric"><b>${Number(d[k]||0).toLocaleString('pt-BR')}</b><small>${l}</small></div>`).join('');$('#systemStatus').textContent='Operacional';$('.status-dot').classList.add('ok')}catch(e){$('#systemStatus').textContent='Verificar sistema';toast(e.message,'error')}}
$('#prospectForm').onsubmit=async e=>{e.preventDefault();try{const data=await api('/api/prospecting/start',{method:'POST',body:JSON.stringify({city:$('#city').value,category:$('#category').value,target:+$('#target').value})});currentJobId=data.job_id;$('#jobTitle').textContent=`${$('#category').value} · ${$('#city').value}`;$('#jobBadge').textContent='rodando';toast('Prospecção iniciada');pollJob()}catch(err){toast(err.message,'error')}};
function renderJob(p={}){const s=p.progress||p;const cells=s.cell_total||Math.max(s.cells||0,1);const idx=s.cell_index||s.cells||0;$('#jobProgress').style.width=`${Math.min(100,Math.round(idx/cells*100))}%`;const vals=[s.new||0,s.known||0,s.cells||0,s.candidates||0];$$('#jobStats b').forEach((b,i)=>b.textContent=vals[i]);$('#jobMessage').textContent=s.company?`Analisando ${s.company}`:s.type==='cell_start'?`Varrendo região ${s.cell_index}/${s.cell_total}`:'Processando cobertura...'}
async function pollJob(){clearTimeout(pollTimer);if(!currentJobId)return;try{const j=await api(`/api/jobs/${currentJobId}`);renderJob(j);if(j.status==='done'){currentRunId=j.result.run_id;$('#jobBadge').textContent='concluído';$('#jobProgress').style.width='100%';$('#jobMessage').textContent=`Concluído: ${j.result.new} novos, ${j.result.known} já conhecidos em ${j.result.cells} regiões.`;toast('Prospecção concluída');loadRunResults();loadDashboard();return}if(j.status==='error'){throw new Error(j.error||'Busca falhou')}pollTimer=setTimeout(pollJob,1500)}catch(e){$('#jobBadge').textContent='erro';$('#jobMessage').textContent=e.message;toast(e.message,'error')}}
$('#includeKnown').onchange=()=>loadRunResults();
async function loadRunResults(){if(!currentRunId)return;try{const rows=await api(`/api/prospecting/runs/${currentRunId}/results?include_known=${$('#includeKnown').checked?1:0}`);$('#runResults').innerHTML=tableHTML(rows,true)}catch(e){toast(e.message,'error')}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function tableHTML(rows,showNew=false){if(!rows.length)return '<p class="empty">Nenhum lead para mostrar.</p>';return `<table><thead><tr><th>Empresa</th>${showNew?'<th>Origem</th>':''}<th>Segmento</th><th>Telefone</th><th>Site</th><th>Score</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(r=>`<tr><td><span class="lead-name">${esc(r.nome)}</span><br><small class="muted">${esc(r.endereco||'')}</small></td>${showNew?`<td><span class="pill ${r.is_new?'new':'known'}">${r.is_new?'novo':'conhecido'}</span></td>`:''}<td>${esc(r.descricao_google||'—')}</td><td>${esc(r.telefone||'—')}</td><td>${r.tem_site?'sim':'não'}</td><td><span class="score">${r.score||0}</span></td><td><span class="pill">${esc(r.status||'novo')}</span></td><td><button class="secondary" onclick="openCompany(${r.id})">Abrir</button></td></tr>`).join('')}</tbody></table>`}
async function loadCRM(){try{const q=encodeURIComponent($('#crmSearch').value||''),st=encodeURIComponent($('#crmStatus').value||''),el=encodeURIComponent($('#crmEligible').value||'');const rows=await api(`/api/companies?q=${q}&status=${st}&eligible=${el}&limit=150`);$('#crmTable').innerHTML=tableHTML(rows)}catch(e){toast(e.message,'error')}}
$('#crmRefresh').onclick=loadCRM;let searchDebounce;$('#crmSearch').oninput=()=>{clearTimeout(searchDebounce);searchDebounce=setTimeout(loadCRM,350)};$('#crmStatus').onchange=loadCRM;$('#crmEligible').onchange=loadCRM;
window.openCompany=async id=>{try{currentCompany=await api(`/api/companies/${id}`);renderDrawer(currentCompany);$('#companyDrawer').classList.add('open')}catch(e){toast(e.message,'error')}};
$('#drawerClose').onclick=()=>$('#companyDrawer').classList.remove('open');$('#companyDrawer').onclick=e=>{if(e.target===$('#companyDrawer'))$('#companyDrawer').classList.remove('open')};
function renderDrawer(c){$('#drawerBody').innerHTML=`<p class="kicker">Lead #${c.id}</p><h2>${esc(c.nome)}</h2><p class="muted">${esc(c.descricao_google||'')} · ${esc(c.endereco||'')}</p><div class="stats-row"><span><b>${c.score||0}</b><small>score</small></span><span><b>${c.vezes_encontrada||1}</b><small>encontrado</small></span><span><b>${c.tem_site?'sim':'não'}</b><small>site</small></span><span><b>${c.wa_eligible?'sim':'não'}</b><small>WA elegível</small></span></div><label>Status<select id="drawerStatus"><option>novo</option><option>qualificado</option><option>contatado</option><option>interessado</option><option>fechado</option><option>perdido</option><option>arquivado</option></select></label><div class="permission-box"><b>Permissão WhatsApp</b><p class="muted">Registre apenas quando houver consentimento verificável.</p><div class="row"><select id="permStatus"><option value="unknown">unknown</option><option value="opted_in">opted_in</option><option value="opted_out">opted_out</option></select><input id="permSource" placeholder="origem: formulário, ligação..."></div><textarea id="permEvidence" rows="2" placeholder="evidência / observação"></textarea><button class="secondary wide" id="savePerm">Salvar permissão</button></div><div class="permission-box"><b>Notas</b><div id="notesList" class="muted">Carregando...</div><textarea id="noteText" rows="2" placeholder="Adicionar observação"></textarea><button class="secondary wide" id="saveNote">Adicionar nota</button></div><div class="drawer-actions"><button class="secondary" id="analyzeBtn">Analisar com IA</button><button class="secondary" id="landingBtn">Gerar landing demo</button><button class="primary" id="messageBtn">Gerar mensagem</button></div><div id="drawerOutput"></div>`;$('#drawerStatus').value=c.status||'novo';$('#drawerStatus').onchange=async()=>{await api(`/api/companies/${c.id}`,{method:'PATCH',body:JSON.stringify({status:$('#drawerStatus').value})});toast('Status atualizado');loadCRM()};$('#savePerm').onclick=async()=>{try{await api(`/api/companies/${c.id}/permission`,{method:'POST',body:JSON.stringify({status:$('#permStatus').value,source:$('#permSource').value,evidence:$('#permEvidence').value})});toast('Permissão registrada');currentCompany=await api(`/api/companies/${c.id}`);renderDrawer(currentCompany);loadCRM()}catch(e){toast(e.message,'error')}};$('#analyzeBtn').onclick=()=>aiAction(`/api/companies/${c.id}/analyze`);$('#messageBtn').onclick=()=>generateMessage(c);$('#landingBtn').onclick=()=>generateLanding(c);loadNotes(c.id);$('#saveNote').onclick=async()=>{try{await api(`/api/companies/${c.id}/notes`,{method:'POST',body:JSON.stringify({text:$('#noteText').value})});$('#noteText').value='';loadNotes(c.id);toast('Nota adicionada')}catch(e){toast(e.message,'error')}}}
async function aiAction(url){const out=$('#drawerOutput');out.innerHTML='<p class="muted">IA processando...</p>';try{const d=await api(url,{method:'POST',body:'{}'});out.innerHTML=`<pre class="ai-output">${esc(d.text||JSON.stringify(d,null,2))}</pre>`}catch(e){out.innerHTML=`<p class="alert error">${esc(e.message)}</p>`}}
async function generateLanding(c){const out=$('#drawerOutput');out.innerHTML='<p class="muted">Gerando landing...</p>';try{const d=await api(`/api/landing/${c.id}`,{method:'POST',body:'{}'});out.innerHTML=`<p><a class="button secondary" target="_blank" href="${esc(d.url)}">Abrir landing</a></p>`;toast('Landing criada')}catch(e){toast(e.message,'error')}}
async function generateMessage(c){const out=$('#drawerOutput');out.innerHTML='<p class="muted">Gerando mensagem...</p>';try{const d=await api(`/api/companies/${c.id}/ai-message`,{method:'POST',body:'{}'});out.innerHTML=`<textarea id="generatedMsg" rows="6">${esc(d.text)}</textarea><div class="drawer-actions"><button class="secondary" id="drySend">Validar envio (dry-run)</button><button class="primary" id="realSend">Enviar</button></div>`;$('#drySend').onclick=()=>sendOne(c,true);$('#realSend').onclick=()=>sendOne(c,false)}catch(e){toast(e.message,'error')}}
async function sendOne(c,dry){try{const d=await api('/api/messages/send',{method:'POST',body:JSON.stringify({ids:[c.id],messages:{[c.id]:$('#generatedMsg').value},dry_run:dry})});const r=d.results?.[0]||{};if(r.blocked)toast(`Bloqueado: ${r.reason}`,'error');else if(r.ok)toast(dry?'Dry-run aprovado':'Mensagem enviada');else toast(r.error||'Falha no envio','error')}catch(e){toast(e.message,'error')}}
async function loadAI(){try{const providers=await api('/api/ai/providers');$('#providerCards').innerHTML=providers.map(p=>`<article class="card provider-card"><p class="kicker">${p.primary?'principal':'fallback'}</p><h2>${p.provider.toUpperCase()}</h2><code>${esc(p.model)}</code><div class="provider-status"><span class="pill ${p.configured?'new':'known'}">${p.configured?'configurado':'sem chave'}</span><button class="secondary" onclick="testProvider('${p.provider}')">Testar</button></div></article>`).join('')}catch(e){toast(e.message,'error')}}
window.testProvider=async p=>{try{const d=await api('/api/ai/test',{method:'POST',body:JSON.stringify({provider:p})});toast(d.ok?`${p}: OK (${d.latency_ms} ms)`:`${p}: ${d.error}`,d.ok?'':'error')}catch(e){toast(e.message,'error')}};
async function loadNotes(id){try{const rows=await api(`/api/companies/${id}/notes`);$('#notesList').innerHTML=rows.length?rows.map(n=>`<p>${esc(n.texto)}<br><small>${esc(n.criado_em||'')}</small></p>`).join(''):'<p>Sem notas.</p>'}catch(e){$('#notesList').textContent=e.message}}
async function loadWhatsApp(){loadInbox();loadTemplates()}
async function loadInbox(){try{const rows=await api('/api/inbox?limit=80');if(!rows.length){$('#inboxTable').innerHTML='<p class="empty">Nenhum evento.</p>';return}$('#inboxTable').innerHTML=`<table><thead><tr><th>Data</th><th>Direção</th><th>Telefone</th><th>Provider</th><th>Status</th><th>Mensagem</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.created_at||'')}</td><td>${esc(r.direction)}</td><td>${esc(r.telefone||'')}</td><td>${esc(r.provider||'')}</td><td><span class="pill">${esc(r.status)}</span></td><td>${esc(r.message_preview||'')}</td></tr>`).join('')}</tbody></table>`}catch(e){toast(e.message,'error')}}
async function loadTemplates(){try{const rows=await api('/api/templates');$('#templateList').innerHTML=rows.length?`<ul class="plain-list">${rows.map(t=>`<li><strong>${esc(t.nome)}</strong> · ${esc(t.mensagem).slice(0,70)}${t.mensagem.length>70?'…':''}</li>`).join('')}</ul>`:'<p>Nenhum template salvo.</p>'}catch(e){toast(e.message,'error')}}
$('#saveTemplate').onclick=async()=>{try{await api('/api/templates',{method:'POST',body:JSON.stringify({name:$('#templateName').value,message:$('#templateMessage').value})});$('#templateName').value='';$('#templateMessage').value='';loadTemplates();toast('Template salvo')}catch(e){toast(e.message,'error')}};$('#refreshInbox').onclick=loadInbox;
async function diagnostics(live){$('#diagOutput').textContent='Executando diagnóstico...';try{const d=await api(`/api/diagnostics?live=${live?1:0}`);$('#diagOutput').textContent=JSON.stringify(d,null,2)}catch(e){$('#diagOutput').textContent=e.message}}
$('#diagLocal').onclick=()=>diagnostics(false);$('#diagLive').onclick=()=>diagnostics(true);
const initial=document.body.dataset.page;tab(initial==='gemini'?'ai':initial==='whatsapp'?'whatsapp':initial==='crm'?'crm':'dashboard');
